# Generated by Django 3.1 on 2021-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название выступления')),
                ('date', models.DateField(verbose_name='Дата выступления')),
                ('place', models.CharField(max_length=255, verbose_name='Название места')),
                ('event_link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
                'ordering': ('-date',),
            },
        ),
    ]
