# Generated by Django 3.1 on 2021-05-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Выступление', 'verbose_name_plural': 'Выступления'},
        ),
    ]
