# Generated by Django 3.1 on 2021-05-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210513_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place_link',
            new_name='place',
        ),
    ]
