# Generated by Django 3.1 on 2021-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210513_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name': 'Выступление', 'verbose_name_plural': 'Выступления'},
        ),
    ]
