# Generated by Django 3.1 on 2021-05-15 17:30

from django.db import migrations, models
import site_settings.models.band_photo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_photo', models.ImageField(upload_to=site_settings.models.band_photo.band_photo_path, verbose_name='Обложка сайта')),
                ('band_photo_bio', models.ImageField(upload_to=site_settings.models.band_photo.band_photo_bio_path, verbose_name='Фотографиия группы в разделе "О группе"')),
            ],
            options={
                'verbose_name': 'Фотография группы',
                'verbose_name_plural': 'Фотография группы',
            },
        ),
    ]
