# Generated by Django 3.1 on 2021-05-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_auto_20210513_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('date',), 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
    ]
