# Generated by Django 3.1 on 2021-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210513_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='is_single',
            field=models.BooleanField(default=0, verbose_name='Сингл'),
        ),
    ]
