# Generated by Django 3.1 on 2021-05-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210513_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название песни')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.release', verbose_name='Релиз')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
    ]
