# Generated by Django 3.1 on 2021-05-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='index_number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер в релизе'),
        ),
    ]
